### ISSUE TITLE
Using external hardware to boost the GRBL

### ISSUE THREAD

**Issue by luben111** [gnea/grbl#105]
Hi,

I have seen many CNC controllers and many of them have dedicated FPGA to generate the STEP/DIR signals. For example on my CNC Sieg KX1 (http://www.arceurotrade.co.uk/Catalogue/Machines-Accessories/CNC-Milling-Machines/Sieg-KX1-CNC-Hobby-Mill/Sieg-KX1-Hobby-CNC-Mill-Bundle) is used LeafBoy controller which is capable to generate 200KHz pulses  
http://leafboy77.com/index.php/en/
![leafboy cnc](https://cloud.githubusercontent.com/assets/5912573/22288149/3e313186-e2fe-11e6-9c94-e9839e64ea05.png)

Do you think it's worth designing such FPGA to improve the performance of GRBL? The FPGA offers ultimate hardware features - we can add any kind of timers and pulse generators inside.  I have a lot of experience in designing FPGA so this should be not that difficult.

**Comment by chamnit** [comment]
@luben111 : Yes. Dedicated FPGA chips are often on industrial machines serving as step/pulse generators for this very same reason. However, the hobby electronic market doesn't really have any FPGA tools and hardware that is cheap, available, or well-supported by the community. The point of Grbl is to make CNC widely accessible, which is why its crammed into an Arduino. 

If you haven't been following the ARM discussion for the next step of Grbl, the next project will be ported to several ARM chips. My early tests on a SAMD21 have been showing nearly 100kHz step rates without USB CDC enabled (comes down to 60kHz with it enabled). Other users have ported Grbl to LPC, which has shown to support over 200kHz easily. Even faster ARM chips would push this higher. There is also the question how high of a step pulse frequency you actually need. For hobby applications, 100kHz will do the job for 99% of applications for most people. You likely don't need anything above 250Khz realistically and ARM chips can do it.

**Comment by luben111** [comment]
I totally agree - GRBL should stay as simple as possible, that's why I really like it :)

**Comment by tdkpipo** [comment]
compañero, si realizaste el proyecton fpga 
necesito el informacion al respecto para un proyecto en mi universidad
