### ISSUE TITLE
Hardware pin to show serial buffer almost filled

### ISSUE THREAD

**Issue by luben111** [gnea/grbl#106]
Hi,

When sending multiple GCode small segments to GRBL for moving over a curve in order to get smooth movement the internal serial buffer should be kept semi filled. I agree that by polling the status of the serial buffer &  planner through <?> it's possible to get idea how much space left and to send or hold the next character (on price of more intensive communication).

What about adding one pin to show the serial buffer is almost filled (for example 2-3 bytes left) - this will allow the USB bridge to hold the data transfer to GRBL but still to accept data from PC (if the internal buffers are large). In case the USB bridge buffers become semi filled it's possible to assert the CTS to prevent the PC for further sending the data.

My point is - the SEMI_FILLED pin could be used for developing a proper USB buffer/bridge for GRBL which can hold more data and will allow the users to move smoothly over curved lines without worrying about lost data. This will allow to simple copy the GCode file to serial COM (with hardware hand shacking) and get the whole task done.

**Comment by chamnit** [comment]
@luben111 : I'm having a hard time seeing how this is useful or how it would simplify things. My experience with flow control is actually the opposite. The tuning of the flow control is dependent on the host computer, as well as other factors, to not overflow the buffers and keep things operating fast. This is because it doesn't account for the overall communication latency of the system very well. Grbl's character counting protocol is much more effective and came about because XON/XOFF software flow control was horrible.
