### ISSUE TITLE
Grbl's character counting protocol

### ISSUE THREAD

**Issue by luben111** [gnea/grbl#110]
In the description of the Grbl's character counting protocol [https://github.com/grbl/grbl/wiki/Interfacing-with-Grbl](url) is shown an example when sending 25, 40, 31, 58 and 20 characters. The algorithm on the PC side counts the sent bytes and knows which commands stay in the GRBL serial buffer, every GRBL response shows that the top stack command was processed and the space in the serial buffer increased by the number of bytes of this particular command.

Here is my question - if PC see that there is not enough space in the buffer to send the next line but there is still some space available,  is it not worth to send partially the next line and when the response come to send the remaining bytes? I don't understand the point for waiting the buffer to have space for one whole line in order to send it, instead we can fill the serial buffer with part of the new line and send the remaining bytes once the response received.

For example when sending 25, 40, 31, 58 and 20 characters with 127 bytes buffer:
1. We send 25, 40 & 31 - total 96 (remaining 31 characters in buffer)
2. Instead of waiting for response we send 31 characters from next line of 58 characters  - once response received we need to send 27 instead 58 characters.

The advantage of this approach is that the communication throughput will increase and become close to hardware handshaking, the price is slightly more sophisticated processing on PC side.

**Comment by chamnit** [comment]
@luben111: There's no reason that it wouldn't work by topping it off at all times. In reality though, you're typically talking about only a dozen bytes or so, since a typical line is about that size. The performance improvement would be very minor and only show up during extremely demanding jobs where it would drain the buffer. I just found it easier to program a streaming script when dealing with single lines. So that's what stuck.
