### ISSUE TITLE
Reset/Abort, Feed/Hold and Cool/Enable, button or circuit breaker?

### ISSUE THREAD

**Issue by marcorighi** [gnea/grbl#116]
Hi,
regarding the functions Reset/Abort, Feed/Hold and Cool/Enable, what is the best solution for you? A button or a circuit breaker? Why? Thanks

**Comment by chamnit** [comment]
@marcorighi : Closing since this isn't a firmware issue. Generally, by default, you should be connecting a normally-open switch to the input pins and recommend placing a small capacitor between the pin and ground to filter noise. I can't give you more than that since I'm not an electrical engineer. You can read the limit pin discussion in a separate issues thread. It's basically the same problem.
