### ISSUE TITLE
Simplifying Joystick/Gamepad Control with Jog Feed Override

### ISSUE THREAD

**Issue by heise** [gnea/grbl#122]
Hello Chamnit,

Thanks for the great additions in #1.1. 

IMHO it would be great to have a feed rate override also in jog mode. It would make things A LOT easier when using a joystick or gamepad with "analog" XY/ZR sticks.

Given the user moves gamepad stick to the right, do the following:

- issue a realtime jog feed override proportional to current stick angle. 
- jog move cmd to the very end of your machine like "$J=G53X500F2000".
- <loop ...>
-  - get new stick angle
-  - send new jog feed override if changed
- <... until user releases stick to neutral>
- send jog cancel $85.

That's it. You don't have to track the machine position since it would not run above indicated move (X500 in this case). It has no latency in any condition. Only pitfall is: you cannot move in diagonal directions with jog, but I don't need that anyway.

I made minor changes in grbl sources to accomplish this. They need about 120 additional bytes.  

I use ASCII realtime chars 0xF1 to 0xFF (gives 15 different override values from 1 to 200 per cent to select an override value pulled from a loook-up table).  0xF0 may reset jog feed override to 100%.
15 speed steps are totally acceptable as they range from 1% to 200% in an exponential curve. This allows very fine positioning as well as fast moves.

Greetings, Carsten

**Comment by chamnit** [comment]
@heise : Understood, but overrides are not supported in jogging mode intentionally. This is to reduce the possibility of a user forgetting the last override they used and having it active when they start a job. That is a recipe for a really bad accident. 

I fully admit that the jogging implementation isn't the best (due to flash and memory constraints), but you have everything you need to do what you want already. I've made a quick demonstration with an analog joystick to make sure prior to releasing v1.1. Just follow the instructions in the jogging wiki. With short jog motions, you'll have better responsiveness and can move in a curve, rather than having to stop and restart a motion in your case.  Just alter the F feed rate. It'll do the same thing when you implement it correctly.
