### ISSUE TITLE
Laser Mode will not activate

### ISSUE THREAD

**Issue by kat0961** [gnea/grbl#164]
When I enter $32=1 in V1.1e, it returns an error saying Setting disabled: Homing cycle failure. Homing is not enabled via settings. I've used two different GUIs but still get an error when I try to activate laser mode.
 Why would homing have anything to do with laser mode?

Thanks

**Comment by chamnit** [comment]
@kat0961 : It doesn't. The setting disabled message needs to be updated to include laser mode being disabled. That's an oversight.

This error occurs if you don't have VARIABLE_SPINDLE enabled in config.h. This is usually due to having a board that has the old v0.8 pin out. Pins D11 and D12 switched to access the hardware PWM on D11 to do the PWM voltage levels.
