### ISSUE TITLE
Axis co-ordinates not changing.

### ISSUE THREAD

**Issue by StuartB4** [gnea/grbl#248]
Sorry about that, pressed enter by mistake and it posted it.

I've just updated my UNO to grbl 1.1 and have a problem with the gcode sending programs I'm using.
I have Universal GCode Sender, Candle, and GRBLController. When moving the X, Y and Z axis nothing changes in the co-ordinate boxes. All 3 programs do the same. Also the virtual indicator in the programs does'nt move.
![untitled](https://user-images.githubusercontent.com/16980026/29242645-7a24d518-7f88-11e7-9a11-e223ba770a63.jpg)
![untitled2](https://user-images.githubusercontent.com/16980026/29242644-7a213b4c-7f88-11e7-9234-d458b9abbc00.jpg)
![untitled3](https://user-images.githubusercontent.com/16980026/29242646-7a26bcfc-7f88-11e7-9cf0-ae54c2f1eecc.jpg)

**Comment by gerritv** [comment]
See Issue #247

**Comment by StuartB4** [comment]
@gerritv: nothing there. That's the one i posted by mistake.

**Comment by gerritv** [comment]
What I wrote there is gone:
Your UGS version is way out of date. in 2015 Gnea/Grbl 1.1 did not exist so it won't support the new reporting format. You will need to ask on that Github because I a) don't use UGS, b) can't make easy sense of what to download that would support 1.1

Candle has a branch for Grbl 1.1

Grbl Controller is abandoned.
