### ISSUE TITLE
How to Use TTL Laser Module?

### ISSUE THREAD

**Issue by TehseenHasan** [gnea/grbl#257]
I am going to buy a 15W Laser Cutting/Engraving Module (From Aliexpress: https://www.aliexpress.com/item/High-Power-Diode-Laser-15W-15000mW-Focusable-Blue-Laser-Module-450-445nm-with-TTL-Driver-for/32757380573.html?spm=a2g0s.9042311.0.0.WLE8pV)
**It is TTL module**... My question is can I use this module with GRBL easily like PWM module to engrave and cut... or I should buy PWM.... How can I wire this TTL module with CNC  shield so that is act like PWM module e.g changeable power, etc.
Please help me about this...Thanks!

**Comment by brakthehun** [comment]
Pin11 (Spindle_enable) is a PWM pin. You wire the TL(TTL_Low) to ground of Arduino and TH(TTL_High) to Pin11 (Spindle_enable) and you can dim it by feeding it an S command from zero to what ever you have $30 at.
Be careful - on old board shields(v3.0 and older),, the z_Limit and Spindle_enable pins are swapped. Because the z_Limit is held high by the arduino,, it may fire the laser and keep it on.

**Comment by TehseenHasan** [comment]
Okay... I will do this... Thanks..!

**Comment by JBSchueler** [comment]
> I am asking this b/c I think so solution proviided by brakthehun was of ttl laser with cnc shield.

as what @brakthehun provided as an answer is correct.
CNC shield or not, pin 11 is the pin to use the laser as TTL input.

**Comment by sp2567** [comment]
I have the opposite problem. My laser is a TTL (no PWM), but my V3 shield has PWM outpout. So my laser works in low power and dont burn anything. When I unconnect the laser from V3 shield works fine. What I must to do?

**Comment by Jibeji** [comment]
As far as it is binary, set it to 200 and you'll be happy forever. :)
