### ISSUE TITLE
PWM min/max seems to have no effect

### ISSUE THREAD

**Issue by Mark-81** [gnea/grbl#277]
Well, I'm sure it's my fault! But I can't understand my mistake. I'm trying gtbl 1.1f in laser mode, constant power (M3). The first thing is to calibrate min and max PWM to get nice shades of gray. I did the following:

1. very simple gcode test:
`G90
F4000
G0 X0 Y0
M3 S0 M8
G4 P2

G91
G1 F2000 X10 S255
X10 S200
X10 S150
X10 S100
X10 S50
X10 S1
G0 X0 Y0.2
G1 X-10 S1
X-10 S50
X-10 S100
X-10 S150
X-10 S200
X-10 S255
G0 X0 Y0.2
....
`

2. set $31=0 $30=255 and give it a try. As expected the lighter shades are not engraved - OK

3. to feel the opposite limits I set $31=200 and $30=255.... the behavior is VERY similar!

The docs says:
`
By default, Grbl linearly relates the max-min RPMs to 5V-0.02V PWM pin output in 255 equally spaced increments. 
`

As far I as understand it should take my input values (0-255, very handy for 8-bit grayscale images by the way) and map them between 200 and 255 in equally spaced increments. It doesn't happen - I still get VERY low power on most shades but the darkest one (that is likely 100%).

How should I calibrate those values for nice shades?

**Comment by biasedlogic** [comment]
@Mark-81
>As far I as understand it should take my input values (0-255, very handy for 8-bit grayscale images by the way) and map them between 200 and 255 in equally spaced increments.

Not quite. The resolution of the PWM is fixed and, due to hardware limitations of the ATmega chip, limited to 8 bits. Hence the step is fixed at about 5V/256 ≈ 20mV. You can map whatever spindle speed range to whatever voltage range, within the accuracy of the math available, but it still will be output rounded to the next 20mV. You are best of using the full output swing and mapping it with an external  circuit to whatever your laser needs
