### ISSUE TITLE
Stream.py del c_line

### ISSUE THREAD

**Issue by saul530** [gnea/grbl#296]
I was running in to an issue with the following code when using the stream.py code as a separate thread on a raspberry pi.

		while sum(c_line) >= RX_BUFFER_SIZE-1 | s.inWaiting() :
			out_temp = s.readline().strip() # Wait for grbl response
			if out_temp.find('ok') < 0 and out_temp.find('error') < 0 :
				print "    MSG: \""+out_temp+"\"" # Debug response
			else :
				if out_temp.find('error') >= 0 : error_count += 1
				g_count += 1 # Iterate g-code counter
				if verbose: print "  REC<"+str(g_count)+": \""+out_temp+"\""
				del c_line[0] # Delete the block character count corresponding to the last 'ok'

I’m not 100% sure what was going on but I suspect some times the program would go in to the while loop because of the s.inWaiting() and would crash because it was there longer than there was entries in c_line.

Not sure if this is the right fix but I have not had any issues after making sure there was an entry before there was a chance of a deletion.

		while sum(c_line) >= RX_BUFFER_SIZE-1 | s.inWaiting() :
			out_temp = s.readline().strip() # Wait for grbl response
			if out_temp.find('ok') < 0 and out_temp.find('error') < 0 :
				print "    MSG: \""+out_temp+"\"" # Debug response
			else :
				if(c_line):
					if out_temp.find('error') >= 0 : error_count += 1
					g_count += 1 # Iterate g-code counter
					if verbose: print "  REC<"+str(g_count)+": \""+out_temp+"\""
					del c_line[0] # Delete the block character count corresponding to the last 'ok'

**Comment by chamnit** [comment]
@saul530 : I regularly use the streaming script for testing and even jobs. On RPis, Macs, and other Linux PCs. I've never run into a performance or reliability issue with the streaming script. I suspect your problem has to do with trying to alter how it works and using in a thread. I can't help you here, because I have no intent of making the streaming script more complicated. It's intentionally designed to be simple so it removes variables for testing.
