### ISSUE TITLE
cycle-stop operation? Confusion how to reset after hold.

### ISSUE THREAD

**Issue by eric-schleicher** [gnea/grbl#413]
I might be missing something but i can't find (or sort out how to achieve something analagous to) a cycle-stop command.  Meaning that when a job is running, this action decelerates the machine and skips hold/alert  states, and does to idle.

...Essentially, a 'just stop where you are' action.

per the wiki docs, it appears this functionality is implemented *only* for the **Jog** operation.  It specifically says that it's ignored if the machine state is **Run**

pleas let me know if i just missed it or can achieve this with a sequence of operation (i can wrap a series of operating in my application).

I've tries issuing `~` and can get the machine into a hold state, but if i issue a <ctlr-x> as soft reset.  even though the machine isn't moving, it shift into an alarm state.

homing is not setup in the configuration, so this behavior doesn't seem to jingle with the docs.
![image](https://user-images.githubusercontent.com/8261783/38753475-60b5d5f0-3f13-11e8-8b68-b30f4cc1aab8.png)
i would expect that if the machine is in a hold state, that issuing the soft reset would but nudge the state back into idle.

Any tips greatly appreciate.

**Comment by chamnit** [comment]
@eric-schleicher : Feed hold and then soft-reset after the machine has come to a complete stop. Grbl will reset without invoking an alarm. It will alarm if the machine is actively moving. 

Even though I know this works as it should. I just tested this again. If you are experiencing something different, please provide all steps, $$ settings, and $I build info output strings, so that I can reproduce this.
