### ISSUE TITLE
Inconsistent output of `ok` when machine status is `hold`

### ISSUE THREAD

**Issue by eric-schleicher** [gnea/grbl#414]
I spend a few hours today chasing down response parsing issues associated with getting status reports when the grbl is in a variety of states.   There may be some other states that behave similairly, but most i verified the output behavior in my own application as well as through universal gcode sender.
```

**Comment by chamnit** [comment]
@eric-schleicher : You'll have to be more specific on what the problem is. Grbl will not respond with an 'ok' all of the time. By design. It will only respond when the command has been parsed and set to be executed. Responses can be held up by the planner queue being full or other circumstances.

That said, there are several dozens of Grbl UI programs, and they work with Grbl just fine. I suspect that you don't quite understand how Grbl behaves and why. Try reading the Interface wiki page.

**Comment by eric-schleicher** [comment]
i accidentally created the ticket before i was ready.   added more detail.

**Comment by chamnit** [comment]
@eric-schleicher : Also, be aware, there only a few minor inconsistencies in Grbl's communication protocol. Mostly due to missing these before v1.1 went to master. The main one is not responding with status reports when in a homing cycle. Others are related to cleaning up some of the responses to be more clear. For the most part, UI developers have been able to easily work around them.

When dealing with a communication protocol, things can't be changed quickly, otherwise all UI would break. Most of these will be addressed in the next major version. If you do find something that is a real problem, the issue can be re-opened and discussed.

**Comment by chamnit** [comment]
Don't send carriage return or line feed characters after real-time command characters. The interface document states this.

**Comment by eric-schleicher** [comment]
Yes, I've read that.  In particular, is there any confirmation that the realtime command has been received/actioned? Or is a success implicit in non-failure of write to the port?  More than willing to edit  the docs to make it clearer.

**Comment by chamnit** [comment]
There is no response to most real-time commands. They are implied from a change in running state in the next status report. Part of this issue is caused by the lack of flash space of the Arduino. 

This is one of the things that I meant by making responses more clear. This is being addressed in the next major version, since flash, memory, and overhead are no longer concerns on an ARM.

**Comment by eric-schleicher** [comment]
Thanks!  I was able to get my application sorted.
