### ISSUE TITLE
grbl return

### ISSUE THREAD

**Issue by sakabin** [gnea/grbl#504]
What should I do if I want to return ok after the g code has finished running?  like home ok

**Comment by chamnit** [comment]
Grbl returns ok when the g-code is parsed and placed into the planner, not after execution. There is an exception to this, when there is a command that requires a planner sync (G4,G10,etc). 

You can simulate what you want two ways. Enable line numbers in config.h and have your UI send line numbers to Grbl with each command. Currently executing line numbers will be available in the status reports and you can track which ones are being processed through that. This is the only way to view things while Grbl is actively running without effecting how things are executed. 

The other way is to insert a 'G4 P0.001' command after each command you are interested in syncing. This will force the planner to empty, complete executing, and return an 'ok' after the G4 dwell command is complete. However, this will cause Grbl to start motion and stop each time you do this, because there will be nothing else in the planner to plan over.
