### ISSUE TITLE
Homing cycle confusion

### ISSUE THREAD

**Issue by czapeczek** [gnea/grbl#545]
Hi. 

I am confused about the homing cycle method. Probably I am doing something wrong but this is too confusing after reading all the specs. 

Normally, homing cycle begins with Z axis and it's pushed all way up. But after homing cycle - the position of the drill is set to -1.00Z -1.00Y and -1.00X I think it should be something like Z-maximum-travel - 1.00 

So what configuration should I use if I want to home to the top of the axis but still have a real machine position?

**Comment by 109JB** [comment]
Machine coordinates are all in negative space. The reason for the Z-axis machine coordinates all being negative actually makes sense because Z=0 is the top of the axis, where on a milling machine it is as far away from anything as possible.  So if you go from one machine to another you can be assured that G53G90G0Z0 will move the spindle up as far as it will go. If you break from this convention, then G53G90G0Z0 goes where?  Crashing right into your table??

 In the same way X=0 and Y=0 are the extreme end of the x and y axis travel, but for these axes it isn't as big a deal regarding negative or positive, so positive or negative doesn't matter as much by since we have a good reason for Z, why not just make it uniform and have x and y in negative space as well..

That said, what the machine coordinates are really doesn't matter because your programs don't use machine coordinates anyway. To use machine coordinates you would have to program a G53 on every line since G53 isn't modal.  Programs use G54-G59 work coordinate systems and these can be zeroed wherever you want. Read up about G54-G59 and you will find that machine coordinates being in all negative space really doesn't matter.
