### ISSUE TITLE
Can i jog during feed hold?

### ISSUE THREAD

**Issue by Harvie** [gnea/grbl#592]
What is the correct procedure to jog while in feed hold mode?

For example, when i have some problems during milling (endmill broken, aluminum welded to it, etc...) and i hit FEED HOLD. Now i want to jog Z axis up, so i can change the endmill, jog back to coordinates where feed hold was hit and resume.

What is correct way of doing this? I want to implement this into bCNC.

**Comment by zeevy** [comment]
No, I think jogging is only possible in machine ideal state

**Comment by chamnit** [comment]
Not possible. But for a reason. The main issue is the change in tool position if you alter to tool at all. If this happens, the proper way to do this is to reset the job, re-probe and re-zero the new tool, and restart the job. 

You can technically do this mid program or at your stop point, but it gets hairy. This requires the GUI to record the exact gcode and parameter states at the stop point. You have to ensure nothing changed like a tool offset or work position origin in the program up to the restart point. Then you have to insert an re-entry path that works with the job, machine setup, and workpiece such that nothing crashes or overloads a tool and intersects the programmed tool path. Then you can continue the job from that point. This is generally the job of the GUI to manage all of this. I have yet to see one but would be nice if bCNC can handle things like this.

**Comment by Harvie** [comment]
I thought that whole point of `$J=` is to isolate jogging commands from the rest of the g-code. Did you considered enabling `$J=` jogging during Hold state?

**Comment by chamnit** [comment]
Allowing jogging during a feed hold still doesn’t solve the issue of re-zeroing a new tool and re-inserting it back into the tool path safely (not every machine or job is the same). 

FWIW, the parking motion (when enabled) will jog the z axis up to a parking position directly over the stop point. It will also turn off the spindle. You can use this to manually clean/inspect the tool. You can even try changing out the tool while parked but you will need some way to manually ensure the tool offset is exactly the same as the one you replaced.

Also, I’ve found that if I allow users too much freedom, they end up grossly misusing the feature to the point where it’s ill advised or even dangerous. A program restart is actually standard on most industrial CNC machines. From what ive seen, they do exactly what I described up above. One reason they do it this way is that it minimizes user error. When there is a user error in their scenarios, it often means personal injury or expensive repairs/remaking a part. I think it’s wise to follow the same standards to learn from their mistakes, even though they are at times frustrating.

**Comment by Harvie** [comment]
> Allowing jogging during a feed hold still doesn’t solve the issue of re-zeroing a new tool 

Yes. I would really love to be able to jog and re-zero Z while in hold mode. This is PITA.

**Comment by Harvie** [comment]
> Allowing jogging during a feed hold still doesn’t solve the issue of re-zeroing a new tool and re-inserting it back into the tool path safely (not every machine or job is the same).

But still this might be usefull. I often get some piece of material coming lose and falling into the cut. So i have to pause the job and get it out, which can be tricky, since there's already endmill in the way and i can't move it during pause... That makes me swear a lot...

**Comment by chamnit** [comment]
You can use the safety door feature. It’ll automatically feed hold, retract, and turn off the spindle. It’ll do the reverse when resumed.

**Comment by 109JB** [comment]
> You can use the safety door feature. It’ll automatically feed hold, retract, and turn off the spindle. It’ll do the reverse when resumed.

Retract?  I was not aware that a retract on door open could be achieved. Other than enabling the safety door in config.h how do you configure to retract?

**Comment by chamnit** [comment]
There are options in the bottom of the config.h file related to something called parking. The default is to retract to 5mm below the top of z. Grbl will enable and disable the spindle about 20mm above the stop point. With enabling, there is a spindle delay to allow it to get to speed before restoring the position and resuming the program.

**Comment by 109JB** [comment]
Nice.  Config.h isn't 100% clear on what happens and when so let me see if I have this right. Sounds like the motion goes something like this

Machine in motion with spindle and coolant running
Door opened
machine comes to controlled stop in X and Y
Z retracts by pullout dist at pullout rate defined in config.h
Z then continues up to 5mm from top of travel (defined in config.h at faster rate defined by parking rate
.    During this motion the spindle and coolant turn off

The once the door is closed and cycle start pushed, the above steps would occur in the revers order.

Is this right?  I just wasn't sure where the spindle and coolant turn on/off.

**Comment by chamnit** [comment]
Correct. The spindle disable and enables at the transition between the pull-out rate and parking rate. When re-enabled, there is a configurable spindle delay before moving back into the part.

**Comment by chamnit** [comment]
There is also a parking real time command, just like feed hold. Can’t recall exactly what it is but I think it’s in the extended ascii character set like the overrides. Should say in the config.h file.

**Comment by langwadt** [comment]
I can see a few tools like a reverse chamfer or treading tool or slitting saw where automatic retract in Z will be  a really bad idea

**Comment by Harvie** [comment]
Yes. Especialy when something already went wrong. I think it's much better to have ability to manualy jog where/how i need. I've been showing GRBL to folks used to work with CNCs like haas and tormach and they couldn't understood how it might lack such feature... Which i can only agree with.

**Comment by chamnit** [comment]
@langwadt : Agreed, which is why it isn't enabled by default. This was a feature requested by vendors for their small machines that just use basic end mills and drills. 

@Harvie :  I asked my machinist friend about this feature. He confirmed your claim that you can jog during a feed hold, as a feature called [run stop job continue](https://haas.co.uk/resources/better-techniques/control-options-general/run-stop-jog-continue/). But, even here, it states you have to be careful how to resume the program, because the return path will use the current offsets and not return on the same path as you jogged away from. 

As I said before, this is most appropriately should be handled by the GUI, not Grbl. Every machine is different and every setup is different. You would have the best control of the machine if the GUI does this same procedure with a cancel, soft-reset, jog the machine or whatever else, and "program restart" at the stop position. I've already described what a "program restart" is in many other posts including this one. Effectively, it is exactly the same thing as what a Haas does.

That said, I do now live near Will Winder, developer of UGS. Perhaps we can work together to implement something like this eventually.

Also, after more thought, it would be impossible for Grbl to institute any new tool offsets or coordinate system changes during a feed hold, which nullifies your basic argument of being able to change out a tool and re-probe it during a feed hold. The reason is: Grbl already has motions queued in the planner with offsets applied. If you set a new offset, all planner motions would need to be perfectly updated, but Grbl does not retain the data to do that due to memory limits. Even if you had the memory to store the complete sets of commands in every planner block, you are introducing tons of edge cases or scenarios for generating an error. The reason pro-CNCs can do this is because they have direct access to the ENTIRE g-code program. It can check to ensure all of the offsets are appropriately applied. For Grbl, you'd have to do it in the way I describe above to ensure it works all properly.

**Comment by 109JB** [comment]
>Yes. Especialy when something already went wrong. I think it's much better to have ability to manualy jog where/how i need. I've been showing GRBL to folks used to work with CNCs like haas and tormach and they couldn't understood how it might lack such feature... Which i can only agree with.

The current Tormach machines use Pathpilot, which at its core is based on LinuxCNC.  You cannot jog LinuxCNC during a feed-hold, and I doubt that you can jog PathPilot.

As for commercial CNC machines, you can hardly compare Grbl to a $100,000 Haas.  Additionally, I worked as a CNC machinist on cemmercial machines, and not all of them can be jogged during feed hold, at least not back when I was making my living using them.

>Also, after more thought, it would be impossible for Grbl to institute any new tool offsets or coordinate system changes during a feed hold, which nullifies your basic argument of being able to change out a tool and re-probe it during a feed hold.

I agree, it would be impossible for Grbl to do it, but it is not impossible for the Grbl Interface program to do this, but not during a feed hold.  I have implemented this in my newest interface that I am writing. It works by having a normal M6 T# command in the program which is intercepted by the interface and other commands inserted such as moving to a predefined too change position, shutting off coolant and spindle, and then waiting for the user to confirm the manual too change is completed.  As I said, it does this "between" programmed lines by inserting appropriate grbl commands. After reading this,

I think I may put the following in my interface where the above could be modified as follows:  

1. Interface detects M6 T999 (T999 would be for tool change with probing to set tool height)
2. Interface inserts commands to raise spindle and move XY to tool change/setter position
3. Interface inserts commands for spindle stop and coolant off
4. Interface opens a dialog box for the user to confirm the tool has been manually changed.
5. Once user confirms, the interface probes to determine TLO of the newly inserted tool (Ideally a tool setter would be mounted on machine in a fixed location)
6. Interface sends G43.1 to Grbl to change TLO
7. Interface then moves Z up

The g-code program would then take over from there.

>The reason pro-CNCs can do this is because they have direct access to the ENTIRE g-code program. It can check to ensure all of the offsets are appropriately applied. For Grbl, you'd have to do it in the way I describe above to ensure it works all properly.

While I agree that you would not be able to change offsets during a feed hold, I would think that jogging alone could possibly be implemented. As it is now the Z axis moves in an automated fashion and returns.  Would it be possible for Grbl to remember the machine XYZ location, and then allow user jogging.  Once resume is pressed then Grbl could move XY first back to the stored machine psoition, then Z?

**Comment by 109JB** [comment]
So I have already implemented this into my new interface program and it was pretty easy to do.  I have not tested with a machine hooked up yet, but have done testing on my arduino test rig that has pushbuttons for simulating the probing.  I still retained the tool change that is accomplished using the tool table, which in my program can hold up to 51 tool definitions and tool length offsets.

So, since this can be accomplished at the interface program level, I would say Grbl is fine the way it is in regard to tool change and setting tool lengths.  It would be a nice feature to have the ability to jog during feed hold, for example to check something during a run, but I personally don't see this as an urgent need.

**Comment by Harvie** [comment]
> As for commercial CNC machines, you can hardly compare Grbl to a $100,000 Haas.

That's because of superior mechanical construction, not because of controller software... If Haas shipped with GRBL i don't think they would be cheaper...

**Comment by MeJasonT** [comment]
109JB,
John when can we beta test your new GUI.

As for the professional quality of GRBL, it may be that the processor isn't as reliable as other micros but it is in no way inferior to the Zilog Z80 or motorolla 68000 and in some cases microchip PICs which will be used in modern industrial machines.
First man on the moon - the Apollo space craft had Zilog Z80s, many industrila machines from the 1970s will have used the motorolla 68000.  In reality the Z80 was an 086 processor where the motorolla 68000 was a 286 predecessor (that's an IBM desktop to us old folk). The Arduino mega has very little difference to the motorola 68000.  Hass and Tormach  have just moved with technology and added a lot of tricky circuitry to make there machines damn reliable.  I have build a few arduino based projects now and managed to slow the processor down so much they have stalled.  GRBL is a piece of genius firmware, I would consider Sonny one of the best programmers on the planet to utilise a small hobby processor to perform what others spend thousands doing is truly remarkable.  i have programmed PLCs and watched guys scratching their heads trying to fix 32 lines of ladder logic roughly 100 nodes.  If Hass built a hobby machine for under $500 they would certainly use GRBL, Sonny don't be surprised if you phone rings.

**Comment by chamnit** [comment]
@109JB: True. Technically Grbl can move during a feed hold, but they do so without an input interface from the user or GUI. The input stream is occupied by the UI during a feed hold so there really isn’t a way to send new jogging commands while a hold is active. It would have to be all through the real-time command interface which is limited and can’t pass target or feed data. 

Supporting motions during a hold would require an update to the streaming interface. Fortunately the new one I’ve been working on would be capable of passing data during a hold. It’s possible to allow this but I wouldn’t allow it as a default option due to the huge potential of misuse by novice users.

**Comment by Harvie** [comment]
> The Arduino mega has very little difference to the motorola 68000. Hass and Tormach have just moved with technology and added a lot of tricky circuitry to make their machines damn reliable.

Yes. If protoneer shield had bunch of optocouplers, the GRBL/Arduino would suddenly seem much more reliable to laymen :-)

> It’s possible to allow this but I wouldn’t allow it as a default option due to the huge potential of misuse by novice users.

I don't get your point. Novice will certainly not be implementing his own GRBL GUI. He will use existing GUI and such GUI should be written in way that it uses GRBL's streaming protocol properly. So what is the problem?

**Comment by 109JB** [comment]
First let me say that I love Grbl, am a huge fan, and have been using if for several years now. It is great for what it is intended for. 

>As for the professional quality of GRBL, it may be that the processor isn't as reliable as other micros but it is in no way inferior to the Zilog Z80 or motorolla 68000 and in some cases microchip PICs which will be used in modern industrial machines.

As much as I love Grbl. it is not in the same caliber as the controls such as Haas or other industrial CNC machine manufacturers employ. I am not referring to the hardware running Grbl, or the the Hass controller. I am referring to the controller "code", regardless of whether the hardware that is running either is comparable or not. As far as I am concerned Grbl is not even in the caliber of the old antiquated industrial controls that I used years ago.  Is Grbl good?  As said, it is great for what it is and for what it is intended to do, but it is lacking in many respects compared to industry. Lack of backlash compensation, screw mapping, closed loop support, cutter radius compensation, spindle synchronization, multi-axis support,  g-code support are just a bit of what even older industrial controls could accomplish. Grbl is written by volunteers who can only devote a certain amount of their spare time to its development. There is not a staff of engineers and programmers working full time on its development. The volunteers have done an amazing job to bring Grbl to where it is, but they just can't compete and I wouldn't expect them to. I do commend them with what they have done.

>That's because of superior mechanical construction, not because of controller software... If Haas shipped with GRBL i don't think they would be cheaper...

You missed my point.  I was referring to this:
>I've been showing GRBL to folks used to work with CNCs like haas and tormach and they couldn't understood how it might lack such feature...

Where you are trying to justify what features an open-source worked on by volunteers very basic controller should have when comparing it to a top of the line industrial control.   Tormach also doesn't have this ability with their new controller, and with Mach3, ... well I have a whole lot of other problems with Mach3.  The fact is, jog during feed hold is not a necessity, but a nice to have.  I worked on industrial controls that didn't allow this on that older industrial iron, and we still seemed to be able to make lots of parts.  

As for the most recent comment it is only partially true.  Yes, a large portion of the price of any industrial machine is based on the mechanical construction, but a portion of the price is definitely based on the control system and is not insignificant.  If Haas suddenly decided to ship their machines with only Grbl, even using the same electronic hardware, then, as much as I love Grbl, I would have to predict the demise of Haas. The control features play a large part in determining a machine's cost. So much so that users may even have to pay a premium to unlock certain features, and the cost to unlock those features isn't trivial. The fact is that Haas employs staff specifically to develop their controllers, the features of those controllers, etc.  I don't expect Grbl to ever be able to compete because it is not a paid for development of Grbl.

>John when can we beta test your new GUI.

Not sure.  I work on it as much as the boss (AKA wife) lets me get away with, but it has a way to go and I would at least want to do some alpha testing before sending it out into the world.

**Comment by Harvie** [comment]
> You missed my point.

You missed mine. You are talking about what GRBL is right now. I am talking about what GRBL CAN be.

**Comment by chamnit** [comment]
@Harvie: And you’ve missed mine. All it takes is a GUI to support a program restart feature. It’s not that hard to implement. I would start lobbying them or come up with your own GUI solution. 

Again, Grbl is just the controller. It requires both a GUI and Grbl to run, unlike a Haas or other CNC solutions which have both integrated.

**Comment by Harvie** [comment]
> All it takes is a GUI to support a program restart feature. It’s not that hard to implement.

Yes. Whole time i was talking about pausing mid-motion, which is something i don't feel like implementing in GUI (eg. pausing in middle of arc motion). But i've realized that it's probably not a big deal, if we just rerun from previous g-code line. Which is already on my TODO list for bCNC. But it will need to do full GRBL reset to clear buffer rather than just feed hold.

@109JB Sorry for offtopic, but how cutter radius compensation works in motion controller? I can imagine compensating cutter radius in CAM, where you are calculating shape offsets according to cutter geometry, but i can't imagine how it would work at g-code level, where is no information about what are you cutting (if cutting at inside or at outside of the shape).

BTW you can get closed loop support on stock unmodified GRBL with proper stepper drivers!
I think mechaduino and similar projects should be perfectly compatible with GRBL and any other motion controller with STEP/DIR outputs:

https://hackaday.com/2016/06/01/mechaduino-closed-loop-stepper-servos-for-everyone/

**Comment by 109JB** [comment]
>You missed mine. You are talking about what GRBL is right now. I am talking about what GRBL CAN be.
We are on github and we are here to develop new features for future releases.

No I completely understand and I appreciate this as a "nice to have feature", but it isn't a "must have" just because many industrial machines have it.  I am absolutely considering what Grbl "could be", but I am considering it in a prioritized fashion. What does Grbl need next. Just because an industrial machine has something should not be an automatic must have, and certainly not a must have next for Grbl. It should be weighed against other needed features in priority. Perhaps it is an easy thing to implement and this ease of implementation pushes it ahead of something else. That is not for me to decide since I can't help with the C/C++ coding of Grbl. Sonny and the others who have that capability are the ones who write the code and determine this priority. I am simply voicing my opinion that this isn't an urgently "needed" feature. There are many many more features that in my opinion are much more important than being able to jog during a feed hold. That feature addresses convenience only. Others such as backlash compensation, more axes, additional g-code support, spindle sync, and cutter comp are a few that address ability rather than just convenience.

**Comment by 109JB** [comment]
>BTW you can get closed loop support on stock unmodified GRBL with proper stepper drivers!

That isn't the type of closed loop support I am referring to. I am referring to closed loop back to the controller. For example, LinuxCNC and industrial controls can close the loop back to themselves. This can be in conjunction with a closed loop drive or in a dual loop fashion. Therefore if one axis slows down it can provide more push to that axis, and/or slow the other axes to maintain correct positioning. Take for example a simultaneous XY move where the X axis lags, but the Y doesn't. This is a case that would happen with only closed loop drives without feedback to the controller. A dual loop feedback system could detect the X axis lag and slow the Y to match.  This isn't trivial, and I really don't think it is something Grbl should aim for, at least in the near term, but is rather just an example of just how advanced industrial controls can be.  As a matter of fact, I am converting a new mill to CNC right now and I am using closed loop steppers where the loop is closed back to the stepper drive. This is fine for 99.99999% of the applications Grbl would be used for and that includes mine.

>@109JB Sorry for offtopic, but how cutter radius compensation works in motion controller? I can imagine compensating cutter radius in CAM, where you are calculating shape offsets according to cutter geometry, but i can't imagine how it would work at g-code level, where is no information about what are you cutting (if cutting at inside or at outside of the shape).

Cutter radius compensation occurs at the programming or CAM level but is implemented at the control level. The way it works is that G41 or G42 cutter radius comp is activated. With G41/G42 a cutter diameter is required much like the tool length for tool length offset. The controller then offsets the driven path from the programmed path by the cutter radius. The side it offsets to is determined by which G41/G42 code is active. This requires at least a one-line look-ahead to see what the next programmed move is so that the end point of the current move can be determined. It gets a bit complicated in implementation because the control that is implementing the compensation needs to determine if it is possible, and if another move needs to be inserted. The programmed path is usually the edge of the part and the offset takes care of the parallel path. Take 2 examples:

1. Lets say a pocket is being milled and a portion of the pocket width is too narrow for the cutter to fit, the controller because of the look ahead recognizes that it can't be accomplished.

2. Say you are milling an outside corner. Normally a straight line is performed on the offset edges with an arc connecting them, The arc is inserted by the controller.

The linuxCNC manual has good description and graphics. Here is a link
http://www.linuxcnc.org/docs/2.5/html/gcode/tool_compensation.html

**Comment by 109JB** [comment]
As an addition to the above 2 descriptions of cutter comp, here is a picture of what those 2 descriptions would look like.

![crc](https://user-images.githubusercontent.com/10978476/53381258-cb65b100-3935-11e9-9cc7-a3a8a3825345.png)

**Comment by Jasonstewart81** [comment]
I see this post say's closed, but hopefully someone can help because the people at Open Builds can't seem to give me an answer to my question. I purchased their Black Box controller and it has a spot to wire in a DOOR switch. Well, unfortunately it doesn't operate the way I was hoping it would like how my old Shapeoko XXL did. The Shapeoko is Grbl based and when you initiate a DOOR OPEN the spindle turns off, the Z axis raises up off the material to a safe distance, and everything pauses. Well with the Open Builds Black Box the DOOR switch indeed turns off the spindle, and pauses everything. That's it though. The bit would still be buried in the material because the Z axis doesn't raise up out of harm's way. I don't understand how if the folks at Carbide 3d made this possible on their machine, why can't Open Builds do it. They both are Grbl v1.1 controllers.

**Comment by 109JB** [comment]
> I see this post say's closed, but hopefully someone can help because the people at Open Builds can't seem to give me an answer to my question. I purchased their Black Box controller and it has a spot to wire in a DOOR switch. Well, unfortunately it doesn't operate the way I was hoping it would like how my old Shapeoko XXL did. The Shapeoko is Grbl based and when you initiate a DOOR OPEN the spindle turns off, the Z axis raises up off the material to a safe distance, and everything pauses. Well with the Open Builds Black Box the DOOR switch indeed turns off the spindle, and pauses everything. That's it though. The bit would still be buried in the material because the Z axis doesn't raise up out of harm's way. I don't understand how if the folks at Carbide 3d made this possible on their machine, why can't Open Builds do it. They both are Grbl v1.1 controllers.

This is a setting in config.h.  The definition of what it does starts on line 551 of config.h.  You basically uncomment line 564

// #define PARKING_ENABLE  // Default disabled. Uncomment to enable

This will enable the parking mode and lines 566-571 define what it does.

**Comment by Jasonstewart81** [comment]
> > I see this post say's closed, but hopefully someone can help because the people at Open Builds can't seem to give me an answer to my question. I purchased their Black Box controller and it has a spot to wire in a DOOR switch. Well, unfortunately it doesn't operate the way I was hoping it would like how my old Shapeoko XXL did. The Shapeoko is Grbl based and when you initiate a DOOR OPEN the spindle turns off, the Z axis raises up off the material to a safe distance, and everything pauses. Well with the Open Builds Black Box the DOOR switch indeed turns off the spindle, and pauses everything. That's it though. The bit would still be buried in the material because the Z axis doesn't raise up out of harm's way. I don't understand how if the folks at Carbide 3d made this possible on their machine, why can't Open Builds do it. They both are Grbl v1.1 controllers.
> 
> This is a setting in config.h. The definition of what it does starts on line 551 of config.h. You basically uncomment line 564
> 
> // #define PARKING_ENABLE // Default disabled. Uncomment to enable
> 
> This will enable the parking mode and lines 566-571 define what it does.

Now if only I knew how to make that change.

**Comment by 109JB** [comment]
> > > I see this post say's closed, but hopefully someone can help because the people at Open Builds can't seem to give me an answer to my question. I purchased their Black Box controller and it has a spot to wire in a DOOR switch. Well, unfortunately it doesn't operate the way I was hoping it would like how my old Shapeoko XXL did. The Shapeoko is Grbl based and when you initiate a DOOR OPEN the spindle turns off, the Z axis raises up off the material to a safe distance, and everything pauses. Well with the Open Builds Black Box the DOOR switch indeed turns off the spindle, and pauses everything. That's it though. The bit would still be buried in the material because the Z axis doesn't raise up out of harm's way. I don't understand how if the folks at Carbide 3d made this possible on their machine, why can't Open Builds do it. They both are Grbl v1.1 controllers.
> > 
> > 
> > This is a setting in config.h. The definition of what it does starts on line 551 of config.h. You basically uncomment line 564
> > // #define PARKING_ENABLE // Default disabled. Uncomment to enable
> > This will enable the parking mode and lines 566-571 define what it does.
> 
> Now if only I knew how to make that change.

Open config.h in a text editor and edit it. You could use notepad on a windows machine. Then re-upload grbl to the machine.

**Comment by Jasonstewart81** [comment]
> > > > I see this post say's closed, but hopefully someone can help because the people at Open Builds can't seem to give me an answer to my question. I purchased their Black Box controller and it has a spot to wire in a DOOR switch. Well, unfortunately it doesn't operate the way I was hoping it would like how my old Shapeoko XXL did. The Shapeoko is Grbl based and when you initiate a DOOR OPEN the spindle turns off, the Z axis raises up off the material to a safe distance, and everything pauses. Well with the Open Builds Black Box the DOOR switch indeed turns off the spindle, and pauses everything. That's it though. The bit would still be buried in the material because the Z axis doesn't raise up out of harm's way. I don't understand how if the folks at Carbide 3d made this possible on their machine, why can't Open Builds do it. They both are Grbl v1.1 controllers.
> > > 
> > > 
> > > This is a setting in config.h. The definition of what it does starts on line 551 of config.h. You basically uncomment line 564
> > > // #define PARKING_ENABLE // Default disabled. Uncomment to enable
> > > This will enable the parking mode and lines 566-571 define what it does.
> > 
> > 
> > Now if only I knew how to make that change.
> 
> Open config.h in a text editor and edit it. You could use notepad on a windows machine. Then re-upload grbl to the machine.

You'll have to forgive me, but i still have no idea where to find config.h

**Comment by 109JB** [comment]
Config.h is one of the files that makes up the source code for GRBL.  You will need to download the source files, make changes as necessary for your application and then upload the source code to your controller. The easiest way is using the Arduino IDE. The steps for doing that are here: https://github.com/gnea/grbl/wiki/Compiling-Grbl

You can download the source by going to the "Code" tab in Github, selecting the green code download button, and selecting download zip. Or just use this link [https://github.com/gnea/grbl/archive/master.zip](url)

As for changes that need to be made to the source code, I cannot guarantee it, but for most folks only settings in config.h need to be changed. There is ample description of each setting in the comment within the config.h file.

Finally, I would recommend that you get yourself a separate controller first. Something like an Arduino Nano, and practice uploading the GRBL firmware to it.  This will get you familiar with the uploading so you don't have to "practice" on your actual machine control board. All you need to do this practice is a USB cable and the Nano. It does not have to be in a machine or anything. You can even "Run" it with whatever control software you use for your actual machine. 

Here is an example of a nano you can buy. [https://www.amazon.com/ATmega328P-Micro-Controller-Arduino-Soldering-Compatible/dp/B08P1DMNLN/ref=sr_1_33?dchild=1&keywords=nano+arduino&qid=1611677823&sr=8-33](url)

**Comment by Jasonstewart81** [comment]
> Config.h is one of the files that makes up the source code for GRBL. You will need to download the source files, make changes as necessary for your application and then upload the source code to your controller. The easiest way is using the Arduino IDE. The steps for doing that are here: https://github.com/gnea/grbl/wiki/Compiling-Grbl
> 
> You can download the source by going to the "Code" tab in Github, selecting the green code download button, and selecting download zip. Or just use this link [https://github.com/gnea/grbl/archive/master.zip](url)
> 
> As for changes that need to be made to the source code, I cannot guarantee it, but for most folks only settings in config.h need to be changed. There is ample description of each setting in the comment within the config.h file.
> 
> Finally, I would recommend that you get yourself a separate controller first. Something like an Arduino Nano, and practice uploading the GRBL firmware to it. This will get you familiar with the uploading so you don't have to "practice" on your actual machine control board. All you need to do this practice is a USB cable and the Nano. It does not have to be in a machine or anything. You can even "Run" it with whatever control software you use for your actual machine.
> 
> Here is an example of a nano you can buy. [https://www.amazon.com/ATmega328P-Micro-Controller-Arduino-Soldering-Compatible/dp/B08P1DMNLN/ref=sr_1_33?dchild=1&keywords=nano+arduino&qid=1611677823&sr=8-33](url)

What about and Arduino uno? I think that's what I have already. I'll have to check when I get home.

**Comment by 109JB** [comment]
Uno would be perfect.

**Comment by Jasonstewart81** [comment]
> Uno would be perfect.

Awesome. Thank you. I'll give that a shot.

**Comment by Jasonstewart81** [comment]
> Config.h is one of the files that makes up the source code for GRBL. You will need to download the source files, make changes as necessary for your application and then upload the source code to your controller. The easiest way is using the Arduino IDE. The steps for doing that are here: https://github.com/gnea/grbl/wiki/Compiling-Grbl
> 
> You can download the source by going to the "Code" tab in Github, selecting the green code download button, and selecting download zip. Or just use this link [https://github.com/gnea/grbl/archive/master.zip](url)
> 
> As for changes that need to be made to the source code, I cannot guarantee it, but for most folks only settings in config.h need to be changed. There is ample description of each setting in the comment within the config.h file.
> 
> Finally, I would recommend that you get yourself a separate controller first. Something like an Arduino Nano, and practice uploading the GRBL firmware to it. This will get you familiar with the uploading so you don't have to "practice" on your actual machine control board. All you need to do this practice is a USB cable and the Nano. It does not have to be in a machine or anything. You can even "Run" it with whatever control software you use for your actual machine.
> 
> Here is an example of a nano you can buy. [https://www.amazon.com/ATmega328P-Micro-Controller-Arduino-Soldering-Compatible/dp/B08P1DMNLN/ref=sr_1_33?dchild=1&keywords=nano+arduino&qid=1611677823&sr=8-33](url)

Well, I found my Sparkfun red board (arduino uno) and uploaded the grbl library to it. All that is fine and uploaded without issues but when I uncomment line #564 I believe I was for PARKING_MODE_ENABLE I get an error when uploading. Honestly I think it's due to this "squiggly" underline I get at the beginning of the config.h file for #include "grbl.h"

**Comment by 109JB** [comment]
What program are you using to edit the config.h?

**Comment by Jasonstewart81** [comment]
> What program are you using to edit the config.h?

Well, windows default to open the file is visual studio, but I tried notepad and WordPad also.

**Comment by 109JB** [comment]
Couldn't find my uno to test and the Nano has 1.5k less memory because they have different bootloaders so not enough to put it on. I'll try to find my Uno tomorrow again and test uploading again.

**Comment by Jasonstewart81** [comment]
> Couldn't find my uno to test and the Nano has 1.5k less memory because they have different bootloaders so not enough to put it on. I'll try to find my Uno tomorrow again and test uploading again.

I actually ordered a new elegoo uno u3 from Amazon, same day delivery. I was able to get the config.h modified and uploaded. I did use notepad++ this time so maybe that helped too. Not sure.

**Comment by 109JB** [comment]
Glad you got it uploaded. Makes me wonder if your machine controller will be ok to upload to.  The firmware image loads fine on my Nano , but is too big with the parking option enabled. I guess worse case, if it is too big it won't load.

**Comment by Jasonstewart81** [comment]
> Glad you got it uploaded. Makes me wonder if your machine controller will be ok to upload to. The firmware image loads fine on my Nano , but is too big with the parking option enabled. I guess worse case, if it is too big it won't load.

Actually Peter with openbuilds wrote me a custom firmware for my Black Box controller because honestly I don't know how to do it.
