### ISSUE TITLE
Pause command (!) doen't stop 3D printer while moving with Python

### ISSUE THREAD

**Issue by SylvenC** [gnea/grbl#667]
I'm controlling my 3D printer as a positioning table using Python
I can send any coordinates as follows: 
s = serial.Serial('COM11',115200) # COM, baudrate
s.write(b'G01 X10')

I want to stop its movement while the printer is still moving by pressing the pause button on the keyboard, as an emergency button.
So have tried using
s.write(b'!')
s.write(b'0x18')
s.write(b'M226')

But my printer doesn't stop moving. It always finishes its previous command and only then listens.

I've tried using Repertier host software to send G Codes like: !  M226 and 0x18
But there it's the same problem.
Am I forgetting something or is it just not possible to stop a movement?

Printer: Creality 3D CR-10 mini 3D printer

**Comment by 109JB** [comment]
Does the printer use Grbl firmware? Doesn't it use Marlin?

If it uses Marlin then there would be the place to ask. I don't know a lot of detail about Marlin but I seem to remember something about an "emergency parser" that you have to activate or something in order to do some things through serial.
