### ISSUE TITLE
How to change startup block on GRBL

### ISSUE THREAD

**Issue by atyanands** [gnea/grbl#671]
Hello all, 
i want to know is there any way in which i can change the starting Block.
my current startup block looks like
[G0 G54 G17 G21 G90 G94 M0 M5 M9 T0 F0. S0.]
i want  M9 and M5 to be replaced by M8 and M4 respectively. 
 Is it possible.? 
The issue i am facing is it starts my spindle (by M9) immediately when i switch on the GRBL. i do not want that. please suggest me anyway better.

**Comment by chamnit** [comment]
See wiki configuration pages. Look for $N command to change the startup blocks. Otherwise update your CAM post. 

 But based on what you said, neither probably won’t help you since your machine is not properly wired for Grbl. M9 should not turn on your spindle. M9 disables coolants. Nor does Grbl take the T word or accept F and S as zero values.
