### ISSUE TITLE
How program the boot loader and program grbl on CAMTOOL 3.3v

### ISSUE THREAD

**Issue by graphtjb** [gnea/grbl#685]
I am posting my findings as i hope this is helpful and presents a straight forward method of updating this board when all else fails. 
This are the document i used to draw my conclusion and produce my method.
https://www.instructables.com/id/Arduino-Leonardo-as-Isp/
http://wiki.sainsmart.com/index.php/101-60-280
http://s3.amazonaws.com/s3.image.smart/download/101-60-280/Schematic_CAMTOOL%20CNC-V3.3.pdf
I turned (or put out of circuit) r19 as this put 220 ohms to ground. R19 ran through a circuit to control an opto-coupler, thus the pin was too grounded to produce high signals on the line. With out MISO programming gets messy. So I am taking r19 out of the circuit for programming and then putting it back in to run the unit. I believe this stopped my programming originally. c46 was also turned to the side (or taken out of circuit). But i don't think it is necessary to take out in order to get the leanardo to program the camtool processor. I solder programming wires for MISO and MOSI directly to the micro controller. I put a pin header on the other end so i could connect them to the lenardo for programming the bootloader and the grbl software..
![IMG_20190710_080913](https://user-images.githubusercontent.com/17986765/60973104-30221680-a2ed-11e9-937c-f08a933ed66a.jpg)
![IMG_20190710_080949](https://user-images.githubusercontent.com/17986765/60973114-3617f780-a2ed-11e9-8538-3b49d0e3372c.jpg)
![IMG_20190710_081052](https://user-images.githubusercontent.com/17986765/60973127-3ca66f00-a2ed-11e9-9c69-b980d6769088.jpg)

**Comment by JBSchueler** [comment]
Hi, normally you have to put an small capacitor like 10uF over the reset signal of the programmer. This prevents the programmer being reseted instead of the device that needs to being programmed.
Maybe it can work without but I was not able to program boards/uP via ISP without the 10uF.

So if you encounter issues when programming, this can be the problem.

[https://www.arduino.cc/en/Tutorial/ArduinoISP](https://www.arduino.cc/en/Tutorial/ArduinoISP)
![image](https://user-images.githubusercontent.com/7997096/60974924-45b63100-a32b-11e9-948a-f958b8c116f8.png)
